CREATE TABLE accounts
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    account_number      VARCHAR(255)                            NOT NULL,
    account_holder_name VARCHAR(255)                            NOT NULL,
    balance             DECIMAL                                 NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

CREATE TABLE transactions
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    source_account_id      BIGINT                                  NOT NULL,
    destination_account_id BIGINT                                  NOT NULL,
    amount                 DECIMAL                                 NOT NULL,
    transaction_time       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status                 VARCHAR(255)                            NOT NULL,
    message                VARCHAR(1000),
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

ALTER TABLE accounts
    ADD CONSTRAINT uc_accounts_accountnumber UNIQUE (account_number);

CREATE INDEX account_number_index ON accounts (account_number);

CREATE INDEX destination_account_id_index ON transactions (destination_account_id);

CREATE INDEX source_account_id_index ON transactions (source_account_id);